### ISSUE TITLE
Searching across multiple indices

### ISSUE THREAD

**Issue by pmarflee** [akade/Akade.IndexedSet#168]
I came across this project and thought it might be useful for a website I'm working on. We have the need to implement a product search where the product catalog is small enough to load into memory, but large enough that an indexed search would yield benefits when compared to a brute-force one.

My question is about what to do when searching across multiple indicies. For example, say I had a `Product` class with the following properties:

* ProductID
* Name
* CategoryID
* Price

And I define the following indices:

* Product ID (unique)
* CategoryID (non-unique)
* Price (range)

If I want to run a search for all products with CategoryID = 5 and Price between 250 & 500, do I have to run two searches? One on the CategoryID index and one on the Price index? And then return the items which intersect both lists?

Many thanks

Paul

**Comment by akade** [comment]
Hey

You don't need to do 2 index lookups but you need to choose the appropriate starting point yourself. Choose the filter (i.e. index) that filters out most candidates as your index lookup.

I.e. if you think that CategoryID = 5 returns a smaller set, then:
`set.Where(x => x.CategoryID, 5).Where(x => x.Price is >250 and <500)`
or vice versa:
`set.Where(x => x.Price, 250, 500).Where(x => x.CategoryID == 5)`

This is exactly what the query planner & execution of a database would do.

There is a third way though, if you have enough memory to throw around and a limited set of combinations (i.e. from filter drop-downs in the UI), you can create compound indices composed of multiple attributes along the following lines:

```csharp
enum PriceRange { Low, Mid, High };

...
PriceRange ToPriceRange(this decimal price) => ...;
...

IndexedSet<Product> set = ...
                          .WithIndex(x => (x.CategoryId, x.Price.ToPriceRange())
                          ...;
 
IEnumerable<Product> result = set.Where(x => (x.CategoryId, x.Price.ToPriceRange(), (5, PriceRange.Mid));
```

Hope that helps :)

**Comment by pmarflee** [comment]
Thanks, that's very helpful.
