### ISSUE TITLE
RobiniaDocs API Explorer

### ISSUE THREAD

**Issue by NeuroXiq** [akade/Akade.IndexedSet#70]
Maybe You will be interested in hosting API Explorer online: 
[www.robiniadocs.com/d/akadeinde](https://www.robiniadocs.com/d/akadeinde/api/Akade.IndexedSet.IndexedSet-1.html)

**Comment by akade** [comment]
As it is open source and MIT, feel free to continue to host the API. Or do I need to do something to maintain that?

**Comment by NeuroXiq** [comment]
Hi,
You dont need to do anythig to maintain that, system will automatically upgrate project for latest nuget packages.
If You want, You can include URL in project README.md file as a badge for other people to see docs :)

[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/akadeinde/api/Akade.IndexedSet.IndexedSet-1.html)

```
[![Static Badge](https://img.shields.io/badge/API%20Docs-DNDocs-43bc00?logo=readme&logoColor=white)](https://www.robiniadocs.com/d/akadeinde/api/Akade.IndexedSet.IndexedSet-1.html)
```
https://github.com/NeuroXiq/RobiniaDocs


Regards
NeuroXiq
